### ISSUE TITLE
Fix first transcription being posted in #transcription_check

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/blossom#133]
**Description:**

The first transcription of each user is posted by Blossom in \#transcription_check for review. However, this is already handled by the welcome team in \#new_volunteers. This could lead to two mods commenting on the same transcription.

Example: https://grafeas.slack.com/archives/CTE1SEPSP/p1622997911092800

**Expected Behaviour:**

The first transcription should be excluded from \#transcription_check.

**Comment by itsthejoker** [comment]
Technically, what gets posted to #new_volunteers is their acceptance of their code of conduct, not their first transcription. I don't see this as a bug, but it's functionality that I'm happy to implement if this is a change the whole team would like to make.

**Comment by MurdoMaclachlan** [comment]
Would it be feasible to have Blossom give a slightly different message in #transcription_check, something like "Welcome team please check u/person's first transcription:"

It's useful having it ping there when they finish because it means we don't have to be constantly checking back to the post if they're taking a long time; we can just see the second ping pop up instead.

**Comment by TimJentzsch** [comment]
That's a fair point, it would be nice to have the connection to the CoC accaptance though, as the mod who claimed that should also review the transcription (and this has to be done by the welcome team, not by user). I like Murdo's idea, or even quoting the original CoC message if that's possible.

**Comment by itsthejoker** [comment]
The easiest way to handle this would be to change the message on the first transcription; I'll throw together a PR as a starting point.

**Comment by TimJentzsch** [comment]
Closed by #136.
